project_id = "mbbxaejkwayrkstyrudr"

[functions.generate-insights]
verify_jwt = true

[functions.extract-products-from-image]
verify_jwt = true

[functions.extract-expense-from-receipt]
verify_jwt = true

[functions.virtual-try-on]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.provision-company-from-checkout]
verify_jwt = false

[functions.financial-chat]
verify_jwt = true

[functions.auth-guard]
verify_jwt = false

