// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-store-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-store-info.ts
var get_store_info_default = defineTool({
  name: "get_store_info",
  title: "Informa\xE7\xF5es da loja",
  description: "Retorna os dados da loja do usu\xE1rio autenticado: nome, slug do cat\xE1logo, WhatsApp, plano contratado e status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("companies").select("id, name, slug, whatsapp_number, plan_tier, plan_status, subscription_end, is_active").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Nenhuma loja vinculada a este usu\xE1rio." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { store: data }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_customers_default = defineTool2({
  name: "list_customers",
  title: "Listar clientes",
  description: "Lista os clientes cadastrados na loja do usu\xE1rio autenticado.",
  inputSchema: {
    search: z.string().optional().describe("Filtro opcional por nome do cliente."),
    limit: z.number().int().optional().describe("M\xE1ximo de clientes a retornar (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("customers").select("id, name, phone, address, notes, created_at").order("name").limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_expenses_default = defineTool3({
  name: "list_expenses",
  title: "Listar despesas",
  description: "Lista as despesas da loja em um per\xEDodo, com t\xEDtulo, categoria, valor e data.",
  inputSchema: {
    start_date: z2.string().optional().describe("Data inicial AAAA-MM-DD."),
    end_date: z2.string().optional().describe("Data final AAAA-MM-DD."),
    category: z2.string().optional().describe("Filtro opcional por categoria."),
    limit: z2.number().int().optional().describe("M\xE1ximo de despesas a retornar (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("expenses").select("id, title, category, amount, expense_date, payment_method, description").order("expense_date", { ascending: false }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (start_date) query = query.gte("expense_date", start_date);
    if (end_date) query = query.lte("expense_date", end_date);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { expenses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_products_default = defineTool4({
  name: "list_products",
  title: "Listar produtos",
  description: "Lista os produtos da loja do usu\xE1rio autenticado, com pre\xE7o, custo e estoque. Permite busca por nome.",
  inputSchema: {
    search: z3.string().optional().describe("Filtro opcional por nome do produto."),
    only_active: z3.boolean().optional().describe("Se true, retorna apenas produtos ativos."),
    limit: z3.number().int().optional().describe("M\xE1ximo de produtos a retornar (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("id, name, price, promotional_price, cost_price, stock, is_active").order("name").limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (search) query = query.ilike("name", `%${search}%`);
    if (only_active) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/low-stock-products.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var low_stock_products_default = defineTool5({
  name: "low_stock_products",
  title: "Produtos com estoque baixo",
  description: "Lista os produtos ativos da loja cujo estoque est\xE1 abaixo de um limite (padr\xE3o: 5 unidades).",
  inputSchema: {
    threshold: z4.number().int().optional().describe("Limite de estoque considerado baixo (padr\xE3o 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ threshold }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const limitValue = threshold ?? 5;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("products").select("id, name, stock, price").eq("is_active", true).lt("stock", limitValue).order("stock");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { threshold: limitValue, products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/sales-summary.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var sales_summary_default = defineTool6({
  name: "sales_summary",
  title: "Resumo de vendas",
  description: "Resumo financeiro da loja em um per\xEDodo: total de vendas, receita, despesas, lucro e produtos mais vendidos.",
  inputSchema: {
    start_date: z5.string().describe("Data inicial no formato AAAA-MM-DD."),
    end_date: z5.string().describe("Data final no formato AAAA-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const startIso = `${start_date}T00:00:00.000Z`;
    const endIso = `${end_date}T23:59:59.999Z`;
    const [salesRes, expensesRes, itemsRes] = await Promise.all([
      supabase.from("sales").select("id, total, created_at").gte("created_at", startIso).lte("created_at", endIso),
      supabase.from("expenses").select("amount, category").gte("expense_date", start_date).lte("expense_date", end_date),
      supabase.from("sale_items").select("product_name, quantity, total_price, sales!inner(created_at)").gte("sales.created_at", startIso).lte("sales.created_at", endIso)
    ]);
    const firstError = salesRes.error ?? expensesRes.error ?? itemsRes.error;
    if (firstError) return { content: [{ type: "text", text: firstError.message }], isError: true };
    const sales = salesRes.data ?? [];
    const expenses = expensesRes.data ?? [];
    const items = itemsRes.data ?? [];
    const revenue = sales.reduce((acc, s) => acc + (Number(s.total) || 0), 0);
    const totalExpenses = expenses.reduce((acc, e) => acc + (Number(e.amount) || 0), 0);
    const byCategory = {};
    for (const e of expenses) byCategory[e.category] = (byCategory[e.category] ?? 0) + (Number(e.amount) || 0);
    const byProduct = {};
    for (const it of items) {
      const entry = byProduct[it.product_name] ??= { quantidade: 0, receita: 0 };
      entry.quantidade += Number(it.quantity) || 0;
      entry.receita += Number(it.total_price) || 0;
    }
    const topProdutos = Object.entries(byProduct).sort((a, b) => b[1].quantidade - a[1].quantidade).slice(0, 10).map(([nome, v]) => ({ nome, ...v }));
    const summary = {
      periodo: { inicio: start_date, fim: end_date },
      moeda: "BRL",
      total_vendas: sales.length,
      receita: revenue,
      despesas: totalExpenses,
      lucro: revenue - totalExpenses,
      despesas_por_categoria: byCategory,
      top_produtos: topProdutos
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mbbxaejkwayrkstyrudr";
var mcp_default = defineMcp({
  name: "lojix",
  title: "Lojix",
  version: "0.1.0",
  instructions: "Ferramentas do Lojix, um SaaS de gest\xE3o de loja (produtos, vendas, despesas, clientes e cat\xE1logo). Todas as ferramentas operam apenas sobre os dados da loja do usu\xE1rio autenticado. Valores monet\xE1rios est\xE3o em BRL. Responda em portugu\xEAs brasileiro.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_store_info_default,
    list_products_default,
    low_stock_products_default,
    list_customers_default,
    list_expenses_default,
    sales_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
